### ISSUE TITLE
2.0.2+1.1.0h break apache-thrift-0.14.1 build

### ISSUE THREAD

**Issue by mingwugmail** [D-Programming-Deimos/openssl#63]
with
	"dependencies": {
		"apache-thrift": "~>0.14.1"
	},

build error:

```
$ dub build --force
Performing "debug" build using /usr/bin/dmd for x86_64.
apache-thrift 0.14.1: building configuration "library"...
/home//.dub/packages/apache-thrift-0.14.1/apache-thrift/lib/d/src/thrift/internal/ssl.d(59,13): Error: undefined identifier X509_V_OK
/home//.dub/packages/apache-thrift-0.14.1/apache-thrift/lib/d/src/thrift/internal/ssl.d(112,14): Error: no property GEN_DNS for type deimos.openssl.x509v3.GENERAL_NAME_st
/home//.dub/packages/apache-thrift-0.14.1/apache-thrift/lib/d/src/thrift/internal/ssl.d(115,14): Error: no property GEN_IPADD for type deimos.openssl.x509v3.GENERAL_NAME_st
/home//.dub/packages/apache-thrift-0.14.1/apache-thrift/lib/d/src/thrift/internal/ssl.d(115,9): Error: duplicate case __error in switch statement
/usr/bin/dmd failed with exit code 1.
```

The previous version: 2.0.1+1.1.0h  works fine.

**Comment by CyberShadow** [comment]
Should be fixed by #64, can you check?

**Comment by CyberShadow** [comment]
CC @1nfiniteloop

**Comment by mingwugmail** [comment]
@CyberShadow  this only fix X509_V_OK.

GEN_DNS and GEN_IPADD still error out.

I tried to add

```
public import deimos.openssl.x509v3;
```

to x509.d, but it does not work.

**Comment by CyberShadow** [comment]
Here is the `#include` dependency graph for the C headers we currently track:

![](https://dump.cy.md/e6e4de3f1c4094dca8c9086cda64e79b/includes.dot.svg)

`GEN_DNS` is declared in `x509v3.h` (and in `x509v3.d` for the D version). However, `x509v3.h` is only included from `ts.h`, `cms.h`, and `oscp.h`, neither of which are included from anywhere else. `thrift.internal.ssl` does not import any of the D versions of these files, so I conclude that `GEN_DNS` being not visible from the current set of imports is the correct and expected behavior.

If it worked previously, then either the old code accidentally allowed it, or the new version mirrored a change in the OpenSSL C headers.

**Comment by mingwugmail** [comment]
https://github.com/apache/thrift/blob/master/lib/d/src/thrift/internal/ssl.d#L27

it directly imported:
```
import deimos.openssl.x509v3;
```

but why on https://github.com/apache/thrift/blob/master/lib/d/src/thrift/internal/ssl.d#L102
```
        case GENERAL_NAME.GEN_DNS:
```

it errors out, saying:

```
ssl.d(102,14): Error: no property GEN_DNS for type deimos.openssl.x509v3.GENERAL_NAME_st
```

something to do with `GENERAL_NAME_st` ?

**Comment by mingwugmail** [comment]
indeed:

in ~/.dub/packages/openssl-2.0.2_1.1.0h/openssl/deimos/openssl/x509v3.d                                                                                                                 

```
struct GENERAL_NAME_st
{
...
}

enum GEN_DNS = 2;    is defined out side of the struct GENERAL_NAME_st!
```

but in the previous version:

~/.dub/packages/openssl-2.0.1_1.1.0h/openssl/deimos/openssl/x509v3.d                                                                                                                 

```
struct GENERAL_NAME_st {

enum GEN_DNS = 2;   // are defined inside the struct!

}
```

Are these 2 files manually edited, or auto-generated?

Anyway, we should keep these `enum`s inside the struct and in the previous version.

**Comment by CyberShadow** [comment]
> it directly imported:

Oops, I missed that. Please ignore my last comment entirely, then.

The corresponding C definitions are:

https://github.com/D-Programming-Deimos/openssl/blob/fc5b9b1847f105397c59e5a3a17ecfded22001d9/C/x509v3.h#L122-L131

An older version of these bindings incorrectly translated those definitions verbatim, placing the `GEN_DNS` etc. definitions in the scope of the struct:

https://github.com/D-Programming-Deimos/openssl/blob/b834a238bf0c7cc5e5d785fd8fb42dbf95b3b456/deimos/openssl/x509v3.d#L177-L187

Obviously this was not correct, because C defines are always globally-scoped.

This was fixed in commit 4fbfe5cf085b9f8456f996be903cd3da23e26a45:

https://github.com/D-Programming-Deimos/openssl/commit/4fbfe5cf085b9f8456f996be903cd3da23e26a45#diff-204e2261b8682deeeda1558ee096a14cf5f04cc2def26fc06b90e73511bcfff5L177

So, the code should be updated accordingly when updating the bindings version.

**Comment by mingwugmail** [comment]
ok, I manually update `GENERAL_NAME.GEN_DNS` to `GEN_DNS`, and it worked.

@CyberShadow , can you merge the PR, and make a new release?


@jfarrell @Jens-G,

Do you mind update the file for the new version of  openssl:

https://github.com/apache/thrift/blob/master/lib/d/src/thrift/internal/ssl.d#L102

BTW, I found I cannot log an issue on: https://github.com/apache/thrift

This makes the issue reporting and discussion difficult, can you enable issue report on https://github.com/apache/thrift ?

Thanks.

**Comment by mingwugmail** [comment]
@CyberShadow I just realized, although 2.0.2+1.1.0h is correct conceptually, but it's a breaking change, i.e. the client code working with pre-2.0.2+1.1.0h is no longer working, 

I think it should have a *major* version update to reflect this fact.

**Comment by CyberShadow** [comment]
> @CyberShadow , can you merge the PR, and make a new release?

Done.

> Do you mind update the file for the new version of openssl:

Why not send a pull request?

> I think it should have a _major_ version update to reflect this fact.

Well, technically the change was a bugfix. The old Thrift code relied on an incorrect translation of the C headers.

BTW, with https://github.com/dlang/dmd/pull/12507 , the entire Deimos project might become obsolete in the near future.

**Comment by WalterBright** [comment]
I will try to obsolete Diemos, but it will take time.

**Comment by mingwugmail** [comment]
@CyberShadow, somehow DUB is not picking up the latest release, it still shows the old version:

https://code.dlang.org/packages/openssl

**Comment by CyberShadow** [comment]
Yes, Dub is like that. You may need to wait a long time until it rescans this repository. I don't have access to the account which registered this repository on Dub to force a rescan.

**Comment by mingwugmail** [comment]
@CyberShadow 

It's 4 days now, dub record still not updated.

In contrast, on dub homepage, it shows

https://code.dlang.org/

Mir is updated 2 hours ago

I think dub scan delay is in hours, not days.

Maybe something wrong with the release tag? Or someone with dub account access can have a check?

**Comment by CyberShadow** [comment]
@s-ludwig Any chance you could have a look at this, please?

**Comment by CyberShadow** [comment]
The release seems to be out.

The problem causing this was probably https://github.com/dlang/dub-registry/pull/496#issuecomment-843792490.

**Comment by Geod24** [comment]
> Well, technically the change was a bugfix. The old Thrift code relied on an incorrect translation of the C headers.

Bugfixes can still be breaking change. Trying to use the latest release of this repo with Vibe.d results in a similar set of error messages:
> vibe-d:tls ~master: building configuration "openssl"...
submodules/vibe.d/tls/vibe/stream/openssl.d(285,45): Error: no property `GEN_DNS` for type `deimos.openssl.x509v3.GENERAL_NAME_st`
submodules/vibe.d/tls/vibe/stream/openssl.d(304,46): Error: no property `GEN_IPADD` for type `deimos.openssl.x509v3.GENERAL_NAME_st`
submodules/vibe.d/tls/vibe/stream/openssl.d(1136,8): Error: no property `GEN_DNS` for type `deimos.openssl.x509v3.GENERAL_NAME_st`
submodules/vibe.d/tls/vibe/stream/openssl.d(1141,8): Error: no property `GEN_IPADD` for type `deimos.openssl.x509v3.GENERAL_NAME_st`
submodules/vibe.d/tls/vibe/stream/openssl.d(1141,3): Error: duplicate `case __error` in `switch` statement
submodules/vibe.d/tls/vibe/stream/openssl.d(1149,33): Error: function `deimos.openssl.x509v3.GENERAL_NAMES_free(stack_st_GENERAL_NAME* a)` is not callable using argument types `(STACK_OF!(GENERAL_NAME_st)*)`
submodules/vibe.d/tls/vibe/stream/openssl.d(1149,33):        cannot pass argument `gens` of type `STACK_OF!(GENERAL_NAME_st)*` to parameter `stack_st_GENERAL_NAME* a`
submodules/vibe.d/tls/vibe/stream/openssl.d(1154,33): Error: no property `GEN_DNS` for type `deimos.openssl.x509v3.GENERAL_NAME_st`
ldc2 failed with exit code 1.
dub build  6.88s user 1.53s system 94% cpu 8.875 total
